name        : libgtop
version     : 2.32.0
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgtop/2.32/libgtop-2.32.0.tar.xz : 8443246332f22b33e389f565825b58cd9623fb7625bf874d404354b705ad178e
license     :
    - GPL-2.0
summary     : GNOME top libraries
description : |
    The libgtop package contains the GNOME top libraries.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
