name       : libgtop
version    : 2.38.0
release    : 12
source     :
    - https://download.gnome.org/sources/libgtop/2.38/libgtop-2.38.0.tar.xz : 4f6c0e62bb438abfd16b4559cd2eca0251de19e291c888cdc4dc88e5ffebb612
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME top libraries
description: |
    The libgtop package contains the GNOME top libraries.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
