name       : libgtop
version    : 2.34.0
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libgtop/2.34/libgtop-2.34.0.tar.xz : 8d8ae39e700d1c8c0b3e1391ed10ca88e6fc14f49d175d516dab6e3313b4ee2a
license    :
    - GPL-2.0
summary    : GNOME top libraries
description: |
    The libgtop package contains the GNOME top libraries.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
