name        : libgtop
version     : 2.30.0
release     : 7
source      :
    - http://ftp.gnome.org/pub/gnome/sources/libgtop/2.30/libgtop-2.30.0.tar.xz : 463bcbe5737b1b93f3345ee34abf601e8eb864f507c49ff1921c2737abafc1e5
homepage    : http://www.gnome.org
license     :
    - GPLv2+
summary     : GNOME top libraries
description : |
    The libgtop package contains the GNOME top libraries.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
