name       : libgtop
version    : 2.40.0
release    : 19
source     :
    - https://download.gnome.org/sources/libgtop/2.40/libgtop-2.40.0.tar.xz : 78f3274c0c79c434c03655c1b35edf7b95ec0421430897fb1345a98a265ed2d4
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME top libraries
description: |
    The libgtop package contains the GNOME top libraries.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
