name       : libgtop
version    : 2.41.1
release    : 20
source     :
    - https://download.gnome.org/sources/libgtop/2.41/libgtop-2.41.1.tar.xz : 43ea9ad13f7caf98303e64172b191be9b96bab340b019deeec72251ee140fe3b
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME top libraries
description: |
    The libgtop package contains the GNOME top libraries.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
